name: Backend Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build the Backend Application
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/aws-key.pem
          chmod 400 ~/.ssh/aws-key.pem  # Ensure the key is only accessible by the current user

      - name: Deploy Backend to AWS EC2
        run: |
          ssh -i ~/.ssh/aws-key.pem ec2-user@your-ec2-public-ip "cd /path/to/backend && git pull && npm install && npm run build && pm2 restart backend"
        env:
          AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
